analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8046595
  brandStrength: 0.8978494
  lightness: 0
  brandColors:
    - '#0F100F'
    - '#888164'
    - '#5D5B4B'
    - '#DED9B4'
  rhythmicContrast: 0.5340502
typography_spectrum: 0.1351815953385085
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6057348
favicon: null
name: UnveiledMoments
